"""
AI Insight model - stores AI-generated insights and analysis.
SQLAlchemy ORM model for PostgreSQL.
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional, List, Dict
from uuid import uuid4

from sqlalchemy import (
    String,
    Text,
    JSON,
    Numeric,
    Index,
    Column,
    Integer,
    Boolean,
    DateTime,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import declarative_base, relationship

from app.db.base import Base


# ===== ENUMS (se mantienen igual, están perfectos) =====

class InsightType(str, Enum):
    """Types of AI insights."""
    ANOMALY_DETECTION = "ANOMALY_DETECTION"
    TREND_ANALYSIS = "TREND_ANALYSIS"
    PREDICTION = "PREDICTION"
    RECOMMENDATION = "RECOMMENDATION"
    CORRELATION = "CORRELATION"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"


class RecommendationLevel(str, Enum):
    """Recommendation urgency levels."""
    INFO = "INFO"
    WARNING = "WARNING"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    CRITICAL = "CRITICAL"


# ===== MODEL (CORREGIDO PARA SQLALCHEMY 2.0 + WINDOWS) =====

class AIInsight(Base):
    """
    AI Insights table.

    Stores insights generated by the AI engine for operational analysis.
    """

    __tablename__ = "ai_insights"

    # ===== PRIMARY KEY =====
    # 🔧 FIX: Usar Column en lugar de Mapped para evitar problemas de resolución de tipos
    id = Column(Integer, primary_key=True, autoincrement=True)

    # ===== INSIGHT IDENTIFICATION =====
    insight_id = Column(String(36), unique=True, nullable=False, index=True, default=lambda: str(uuid4()))

    # ===== INSIGHT CLASSIFICATION =====
    insight_type = Column(String(50), nullable=False, index=True)
    anomaly_type = Column(String(100), nullable=True)

    # ===== SOURCE CONTEXT =====
    source_service = Column(String(100), nullable=False, index=True)
    source_event_id = Column(String(36), nullable=True)
    correlation_id = Column(String(36), nullable=True)

    # ===== INSIGHT CONTENT =====
    title = Column(String(255), nullable=False)
    summary = Column(Text, nullable=True)
    description = Column(Text, nullable=False)

    # ===== CONFIDENCE AND SCORING =====
    # 🔧 FIX: Numeric(5,4) permite valores de 0.0000 a 9.9999 (perfecto para confidence_score)
    confidence_score = Column(Numeric(5, 4), nullable=False, default=Decimal("0.0000"))
    impact_score = Column(Numeric(5, 4), nullable=True)

    # ===== RECOMMENDATION =====
    recommendation_level = Column(
        String(30),
        nullable=False,
        default=RecommendationLevel.INFO.value,
        index=True,
    )
    recommendation = Column(Text, nullable=True)

    # 🔧 FIX CRÍTICO: NO usar Mapped[list[str]] con JSON en Windows + Python 3.14
    # SQLAlchemy no resuelve la anotación de tipo automáticamente
    action_items = Column(JSON, nullable=True, default=list)

    # ===== RELATED DATA =====
    # 🔧 FIX: Usar JSON directo, sin Mapped[dict[...]]
    affected_resources = Column(JSON, nullable=True, default=list)
    related_metrics = Column(JSON, nullable=True, default=dict)

    # ===== MODEL INFORMATION =====
    model_provider = Column(String(50), nullable=True)
    model_name = Column(String(100), nullable=True)

    # ===== FEEDBACK LOOP =====
    feedback_rating = Column(Integer, nullable=True)  # 1-5
    feedback_comment = Column(Text, nullable=True)

    # ===== STATUS =====
    is_acknowledged = Column(Boolean, default=False, index=True)
    acknowledged_by = Column(String(36), nullable=True)

    # 🔧 FIX: acknowledged_at debe ser DateTime, no String
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)

    # ===== TEMPORAL FIELDS (FALTABAN PERO SE USABAN EN ÍNDICES) =====
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # ===== INDEXES =====
    __table_args__ = (
        Index("ix_ai_insights_type_confidence", "insight_type", "confidence_score"),
        Index("ix_ai_insights_source_level", "source_service", "recommendation_level"),
        Index("ix_ai_insights_acknowledged", "is_acknowledged", "created_at"),
        # 🔧 Índice adicional para búsquedas por servicio + tipo
        Index("ix_ai_insights_service_type", "source_service", "insight_type"),
    )

    def __repr__(self) -> str:
        return (
            f"<AIInsight(id={self.id}, insight_id={self.insight_id}, "
            f"type={self.insight_type}, confidence={self.confidence_score})>"
        )

    # ===== UTILS =====

    def to_dict(self) -> dict:
        """Convert insight to dictionary for API responses."""
        return {
            "id": self.id,
            "insight_id": self.insight_id,
            "insight_type": self.insight_type,
            "anomaly_type": self.anomaly_type,
            "source_service": self.source_service,
            "source_event_id": self.source_event_id,
            "correlation_id": self.correlation_id,
            "title": self.title,
            "summary": self.summary,
            "description": self.description,
            "confidence_score": float(self.confidence_score) if self.confidence_score else None,
            "impact_score": float(self.impact_score) if self.impact_score else None,
            "recommendation_level": self.recommendation_level,
            "recommendation": self.recommendation,
            "action_items": self.action_items or [],
            "affected_resources": self.affected_resources or [],
            "related_metrics": self.related_metrics or {},
            "model_provider": self.model_provider,
            "model_name": self.model_name,
            "feedback_rating": self.feedback_rating,
            "feedback_comment": self.feedback_comment,
            "is_acknowledged": self.is_acknowledged,
            "acknowledged_by": self.acknowledged_by,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def is_critical(self) -> bool:
        """Check if insight requires immediate attention."""
        return (
                self.recommendation_level == RecommendationLevel.CRITICAL.value
                and self.confidence_score >= Decimal("0.8000")
        )

    def requires_acknowledgment(self) -> bool:
        """Check if insight needs human acknowledgment."""
        return self.recommendation_level in [
            RecommendationLevel.ACTION_REQUIRED.value,
            RecommendationLevel.CRITICAL.value,
        ] and not self.is_acknowledged