"""
Repository for AI Insights.
Provides specialized queries for insight data.
"""

from datetime import datetime
from typing import Any, List, Optional
from sqlalchemy import select, and_, func, desc
from sqlalchemy.ext.asyncio import AsyncSession

# 🔧 Mock temporal de AIInsight si el modelo no existe aún
# (Se elimina cuando app/db/models/ai_insight.py esté listo)
try:
    from app.db.models.ai_insight import AIInsight
except ImportError:
    # Mock mínimo para que el backend arranque sin bloqueos
    from sqlalchemy.orm import declarative_base
    from sqlalchemy import Column, String, Float, DateTime, UUID, Text, Boolean
    import uuid

    Base = declarative_base()


    class AIInsight(Base):  # type: ignore
        __tablename__ = "ai_insights"
        id = Column(UUID, primary_key=True, default=uuid.uuid4)
        confidence_score = Column(Float, nullable=False)
        anomaly_type = Column(String(50), nullable=True)
        source_service = Column(String(100), nullable=False)
        recommendation_level = Column(String(20), nullable=False)
        timestamp = Column(DateTime(timezone=True), server_default=func.now())
        insight_text = Column(Text, nullable=True)
        is_active = Column(Boolean, default=True)

from app.repositories.base import BaseRepository


class InsightRepository(BaseRepository[AIInsight]):
    """
    Repository for AI insights.

    Provides specialized queries for insight data with filtering,
    scoring, and temporal analysis capabilities.
    """

    def __init__(self, session: AsyncSession) -> None:
        super().__init__(AIInsight, session)

    async def get_by_insight_id(self, insight_id: str) -> Optional[AIInsight]:
        """
        Get insight by its unique insight_id.

        Args:
            insight_id: Unique insight identifier

        Returns:
            Insight instance or None
        """
        return await self.get_by_field("id", insight_id)

    async def get_by_source_service(
            self,
            source_service: str,
            skip: int = 0,
            limit: int = 100,
    ) -> List[AIInsight]:
        """
        Get insights generated by a specific service.

        Args:
            source_service: Service name that generated the insight
            skip: Records to skip (pagination)
            limit: Max records to return

        Returns:
            List of insights
        """
        result = await self.session.execute(
            select(AIInsight)
            .where(AIInsight.source_service == source_service)
            .order_by(desc(AIInsight.timestamp))
            .offset(skip)
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_by_confidence_range(
            self,
            min_confidence: float,
            max_confidence: float,
            skip: int = 0,
            limit: int = 100,
    ) -> List[AIInsight]:
        """
        Get insights within a confidence score range.

        Args:
            min_confidence: Minimum confidence score (0.0 to 1.0)
            max_confidence: Maximum confidence score (0.0 to 1.0)
            skip: Records to skip
            limit: Max records to return

        Returns:
            List of insights
        """
        result = await self.session.execute(
            select(AIInsight)
            .where(
                and_(
                    AIInsight.confidence_score >= min_confidence,
                    AIInsight.confidence_score <= max_confidence,
                )
            )
            .order_by(desc(AIInsight.confidence_score))
            .offset(skip)
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_by_anomaly_type(
            self,
            anomaly_type: str,
            skip: int = 0,
            limit: int = 100,
    ) -> List[AIInsight]:
        """
        Get insights filtered by anomaly type.

        Args:
            anomaly_type: Type of anomaly (e.g., "latency_spike", "error_rate")
            skip: Records to skip
            limit: Max records to return

        Returns:
            List of insights
        """
        result = await self.session.execute(
            select(AIInsight)
            .where(AIInsight.anomaly_type == anomaly_type)
            .order_by(desc(AIInsight.timestamp))
            .offset(skip)
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_recent_insights(
            self,
            hours: int = 24,
            skip: int = 0,
            limit: int = 100,
    ) -> List[AIInsight]:
        """
        Get insights generated within the last N hours.

        Args:
            hours: Time window in hours
            skip: Records to skip
            limit: Max records to return

        Returns:
            List of recent insights
        """
        cutoff = datetime.utcnow()
        from datetime import timedelta
        cutoff = cutoff - timedelta(hours=hours)

        result = await self.session.execute(
            select(AIInsight)
            .where(AIInsight.timestamp >= cutoff)
            .order_by(desc(AIInsight.timestamp))
            .offset(skip)
            .limit(limit)
        )
        return list(result.scalars().all())

    async def create_insight(
            self,
            confidence_score: float,
            source_service: str,
            recommendation_level: str,
            anomaly_type: Optional[str] = None,
            insight_text: Optional[str] = None,
            **kwargs: Any,
    ) -> AIInsight:
        """
        Create a new AI insight.

        Args:
            confidence_score: Confidence level (0.0 to 1.0)
            source_service: Service that generated this insight
            recommendation_level: Action level (e.g., "investigate", "alert", "ignore")
            anomaly_type: Optional type of anomaly detected
            insight_text: Optional human-readable explanation
            **kwargs: Additional fields

        Returns:
            Created insight instance
        """
        data = {
            "confidence_score": confidence_score,
            "source_service": source_service,
            "recommendation_level": recommendation_level,
            "anomaly_type": anomaly_type,
            "insight_text": insight_text,
            **kwargs,
        }
        return await self.create(data)

    async def count_by_source(self, source_service: str) -> int:
        """
        Count insights generated by a specific service.

        Args:
            source_service: Service name

        Returns:
            Count of insights
        """
        result = await self.session.execute(
            select(func.count())
            .where(AIInsight.source_service == source_service)
        )
        return result.scalar_one() or 0

    async def count_by_confidence_threshold(self, threshold: float) -> int:
        """
        Count insights above a confidence threshold.

        Args:
            threshold: Minimum confidence score

        Returns:
            Count of high-confidence insights
        """
        result = await self.session.execute(
            select(func.count())
            .where(AIInsight.confidence_score >= threshold)
        )
        return result.scalar_one() or 0

    async def deactivate_insight(self, insight_id: str) -> bool:
        """
        Soft-delete an insight by setting is_active=False.

        Args:
            insight_id: ID of the insight to deactivate

        Returns:
            True if updated, False if not found
        """
        insight = await self.get_by_field("id", insight_id)
        if insight and hasattr(insight, "is_active"):
            insight.is_active = False  # type: ignore
            await self.session.commit()
            return True
        return False